### ISSUE TITLE
Trine Enchanted Edition

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#50] opened 2024-11-25 04:44 UTC
## Description

`Playable`
[log.txt](https://github.com/user-attachments/files/17897136/log.txt)

## Screenshots
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 33 14" src="https://github.com/user-attachments/assets/4bf89292-0da6-456e-b8b5-e504671fab3e">shadows of trees and character in the foreground
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 34 05" src="https://github.com/user-attachments/assets/02efe4f8-595f-421d-9e40-551667fc5607">light in the foreground
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 35 13" src="https://github.com/user-attachments/assets/230aa763-8e5e-4013-9306-902b8e5f36fb">light and shadow in the foreground
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 33 21" src="https://github.com/user-attachments/assets/f1f2dfea-3a1e-4392-b9a5-5d7848bb1b05">text is missing

https://www.youtube.com/watch?v=kGRpeUDQ0wE

## Cemu Metal version

`testing1.0.6`

## Mac

Put the Mac model you used for testing here (e.g. `M1 MacBook Air`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment] 2024-11-25 06:10
Does the missing text issue happen on Vulkan as well? Might be the same problem with missing fonts as in Mario Maker

**Comment by darkuser89** [comment] 2024-11-25 10:10
ingame = https://www.mediafire.com/file/tpdzxjk22p83f5f/Cemu_release.gputrace.zip/file
yes ist the same 
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 11 04 30" src="https://github.com/user-attachments/assets/0feaa918-5129-44a2-9014-cc2396f0c048">

**Comment by SamoZ256** [comment] 2024-11-25 14:56
I'd appreciate a frame capture on Vulkan of the lights and shadows (it it works on it). I think I know where the issue happens, I just need something to compare it with to know exactly what went wrong

**Comment by darkuser89** [comment] 2024-11-25 15:17
also in this game vulkan looks the same

**Comment by SamoZ256** [comment] 2024-11-25 15:32
I just looked up a footage of this game online and it seems like the issue isn't exclusive to macOS. I am going to close this issue.

**Closed** 2024-11-25 15:32 UTC
Labels: playable
