### ISSUE TITLE
TEKKEN TAG TOURNAMENT 2 Wii U EDITION

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#57] opened 2024-11-28 22:32 UTC
## Description

`Playable`
When you choose a character for the first time, they have small errors. Pic 1
but if you choose the character again everything is normal
even minor image errors (pic 2) are gone if you choose the character in another fight

## Screenshots
<img width="1231" alt="Bildschirmfoto 2024-11-28 um 23 20 50" src="https://github.com/user-attachments/assets/4ec63af6-dba2-4138-b6e5-78d2c34b9e4a">
<img width="1231" alt="Bildschirmfoto 2024-11-28 um 23 26 02" src="https://github.com/user-attachments/assets/bf3e6754-9483-4c30-8ac2-0b4c34a15a07">
<img width="1231" alt="Bildschirmfoto 2024-11-28 um 23 26 41" src="https://github.com/user-attachments/assets/7e1d8014-1803-4b11-88f6-d41c982f1dbb">

## Cemu Metal version

`testing1.0.6`

## Mac

M3 Pro

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment] 2024-11-29 08:57
The issues with characters may be due to async compile. Are the issues gone after you reopen Cemu? Also, did you test it with testing1.0.5 or is that a mistake?

**Comment by darkuser89** [comment] 2024-11-29 10:35
yes I tested it with 1.0.6 after restarting the emulator everything looks fine

**Comment by SamoZ256** [comment] 2024-11-29 11:40
According to the Cemu wiki, Vulkan has the same issue with async enabled, so I will close this issue

**Comment by shinra-electric** [comment] 2024-12-11 19:57
Tested `1.0.9`: Screen freezes after selecting a character in `Offline Mode` --> `Arcade Battle`. Tried some other modes too, like `Practice`. 

The game is still running in the background, as I can select a a second character in tag mode, and can hear my inputs played out in the fight through the audio. 
[log.txt](https://github.com/user-attachments/files/18101406/log.txt)
[TTT2Terminal.txt](https://github.com/user-attachments/files/18101407/TTT2Terminal.txt)
![Screenshot 2024-12-11 at 19 49 22](https://github.com/user-attachments/assets/709daa79-53c2-4838-9b79-9fbc55c3256e)
I noted that if it is compiling a shader, the compilation notification also freezes. 

Because the OP got in-game with `1.0.6` I tried that too, but it still froze. 

M1 Pro / Sequoia 15.1.1

**Comment by darkuser89** [comment] 2024-12-11 21:29
https://youtu.be/DUSlF3G6VIg

For me the fights started without any problems.
apart from the small problems from above.

**Comment by darkuser89** [comment] 2024-12-13 05:31
frame = https://www.mediafire.com/file/0z8bgz5xtxrx7p2/m1max152.zip/file
M1 Max // 15.2

**Comment by SamoZ256** [comment] 2024-12-13 16:15
@darkuser89 what is the frame capture for exactly?

**Comment by darkuser89** [comment] 2024-12-13 16:28
shinra-electric reported that the game hangs on an m1. I then tested it on an m1 max. But on an m3 pro it starts without any problems.

**Comment by SamoZ256** [comment] 2024-12-13 16:30
And did it freeze on M1 Max?

**Comment by darkuser89** [comment] 2024-12-13 17:07
After selecting the characters, the image freezes and runs in the background.

Even Call of Duty Black Ops 2 doesn't start on an M1 Max, although it starts on an M3 Pro for me.

**Comment by SamoZ256** [comment] 2024-12-13 17:35
Do both of those machines run the same macOS version?

**Comment by darkuser89** [comment] 2024-12-13 17:56
yes I have both 15.2

**Comment by SamoZ256** [comment] 2024-12-13 18:08
I suspect this is a GPU hang. I would be very grateful if you launched it through Xcode and send me whatever gets printed out to the console (it should be in the bottom right corner)

**Comment by darkuser89** [comment] 2024-12-13 18:59
[m1maxttt.txt](https://github.com/user-attachments/files/18130703/m1maxttt.txt)

**Comment by SamoZ256** [comment] 2024-12-14 06:18
Ok, it’s a GPU hang, but a very strange one.

**Comment by SamoZ256** [comment] 2024-12-14 09:57
Could you please run [this build](https://drive.google.com/file/d/1JrnkHq5UhOtW6lP3NJzYT8S5fRh9mc-Q/view?usp=sharing)? It won't fix it, but it will contain some useful info in the log

**Comment by darkuser89** [comment] 2024-12-14 16:39
[log.txt](https://github.com/user-attachments/files/18136773/log.txt)
[xcodettterror2.txt](https://github.com/user-attachments/files/18136774/xcodettterror2.txt)

**Comment by SamoZ256** [comment] 2024-12-14 17:18
Seems like I forgot to add safety checks for color attachment clears. Fingers crossed for [this build](https://drive.google.com/file/d/1Il6aaLNtvXs73psLrOLO42sQ382LBRyy/view?usp=sharing).

**Comment by darkuser89** [comment] 2024-12-14 17:32
<img width="1392" alt="Bildschirmfoto 2024-12-14 um 18 29 50" src="https://github.com/user-attachments/assets/306f44a6-40c1-4a2d-898e-f857c0fa64b6" />
<img width="1392" alt="Bildschirmfoto 2024-12-14 um 18 31 19" src="https://github.com/user-attachments/assets/fbc844b9-31ba-4ddb-b5a8-d145f7359835" />
#
now it works on the m1 :-)

**Comment by SamoZ256** [comment] 2024-12-14 19:09
Great to see it works now! It was truly a strange issue, and the error messages made it seem like it was a compile failure. Anyway, what do you mean by Stat Generic? The Debug Overlay? I'd like to implement GPU selecting like on Vulkan, though there wasn't really a need for that, since the vast majority of Macs have only a single GPU

**Comment by shinra-electric** [comment] 2024-12-14 19:21
I can confirm that the test build fixes it on my M1 Pro 👍🏼

I think that darkuser is talking about the `Graphic Device` in the settings? I'm not sure though...

![Screenshot 2024-12-14 at 19 19 58](https://github.com/user-attachments/assets/ed8d7c6f-a272-42dd-9283-1957298a3c29)
![Screenshot 2024-12-14 at 19 20 04](https://github.com/user-attachments/assets/82558917-fb98-4485-acd3-19a93338d142)

**Closed** 2024-12-15 05:39 UTC
Labels: playable

**Comment by mrdc** [comment] 2025-06-08 12:46
I’ve seen once vertex explosions making the round completely unplayable.
And some missing textures/invisible parts on characters.
Will add screenshots/video later.

**Comment by mrdc** [comment] 2025-06-08 12:47
@SamoZ256 Can we reopen this issue?

**Comment by shinra-electric** [comment] 2025-06-08 18:22
That may be due to the async issues, if they don't occur a second time.

However when I went back to test, I did notice some over-exposed bloom that I hadn't noticed before, only on the Poland stage:

![Image](https://github.com/user-attachments/assets/3479c2b0-71fa-4491-9306-1e8b32baae17)

I haven't noticed it on any other stages (yet).

Edit: 

Actually, it's the same as Vulkan, so this wouldn't be a Metal-specific issue:

![Image](https://github.com/user-attachments/assets/5e9b8186-0d59-479c-a6dc-fe520aa754ee)
